Lakka: move LIBRETRO_CORES to own package
when cores are set via virtual package, one can filter out cores also
based on other circumstances. in distro-options only PROJECT, DEVICE and
ARCH are available, so one cannot disable core based on OPENGL/OPENGLES,
VULKAN etc.

diff --git a/distributions/Lakka/show_config b/distributions/Lakka/show_config
--- a/distributions/Lakka/show_config
+++ b/distributions/Lakka/show_config
@@ -18,6 +18,13 @@ show_distro_config() {
   if [ "${DISABLE_LIBRETRO_CORES}" = "yes" ]; then
     config_message+="\n  Building without any libretro cores!"
   else
+    # source the libretro_cores package
+    if [ ! -f ${ROOT}/packages/lakka/libretro_cores/package.mk ]; then
+      echo "FAILURE: Cannot find packages/lakka/libretro_cores/package.mk!"
+      exit 1
+    fi
+    . ${ROOT}/packages/lakka/libretro_cores/package.mk
+    echo LIBRETRO_CORES=${LIBRETRO_CORES}
     declare -i count=0
     for pkg in ${LIBRETRO_CORES} ; do count+=1 ; done
     config_message+="\n  Including ${count} libretro core(s)"
